version: '3.9'
services:
  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes: 
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  # used to preview data stored in the database
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
